--# 실전문제 (짝수)

--# 2. 사원번호, 사원이름, 부서이름 검색(EQUL JOIN)
SELECT * FROM EMP;
SELECT EMP.EMPNO, ENAME, DEPT, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;

--# 4. 사원번호, 사원이름, 부서 이름 검색(JOIN~USING)
SELECT EMPNO, ENAME, DEPT.DNAME FROM EMP JOIN DEPT USING(DEPTNO);

--# 6. 지역이 NEW YORK인 사원이름을 검색하라( EQUL JOIN)
SELECT ENAME, LOC FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND LOC = 'NEW YORK';

--# 8. 지역이 NEW YORK인 사원 이름을 검색하라(JOIN ~ USING)
SELECT ENAME, LOC FROM EMP JOIN DEPT USING(DEPTNO) WHERE LOC = 'NEW YORK';

--# 10. 지역이 NEW YORK인 사원의 사원번호, 사원이름을 사원번호 순으로 검색
SELECT EMPNO, ENAME, LOC FROM EMP JOIN DEPT USING(DEPTNO) WHERE LOC = 'NEW YORK' ORDER BY EMPNO;

--# 12. ADAMS 사원이 근무중인 부서이름과 지역을 검색하라(JOIN ~ USING)
SELECT ENAME, DNAME, LOC FROM EMP JOIN DEPT USING(DEPTNO) WHERE ENAME = 'ADAMS';

--# 13. ADAMS 사원이 근무중인 부서이름과 지역을 검색( JOIN ~ ON) 
SELECT ENAME, DNAME, LOC FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE ENAME = 'ADAMS';

--# 14. ADAMS 사원이 근무중인 부서이름과 지역을 검색(NATURAL JOIN)
SELECT ENAME, DNAME, LOC FROM EMP NATURAL JOIN DEPT WHERE ENAME = 'ADAMS';

--# 16. 급여가 1000이상 2000이하인 사원들의 사원번호, 사원이름, 부서이름을 사원번호순으로 검색

SELECT EMPNO, ENAME, DNAME, SAL FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL BETWEEN 1000 AND 2000 ORDER BY 1;
SELECT EMPNO, ENAME, DNAME, SAL FROM EMP NATURAL JOIN DEPT WHERE SAL BETWEEN 1000 AND 2000 ORDER BY 1;

-- JOIN ~USING
SELECT EMPNO, ENAME, DNAME, SAL FROM EMP JOIN DEPT USING(DEPTNO) WHERE SAL BETWEEN 1000 AND 2000 ORDER BY 1;
-- JOIN ~ ON
SELECT EMPNO, ENAME, DNAME, SAL FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE SAL BETWEEN 1000 AND 2000 ORDER BY 1;

--# 18. NEW YORK이나 DALLAS 지역에 근무하는 사원들의 사원번호와 사원이름을 사원번호 순으로 검색(EQUL JION)
SELECT * FROM EMP;
SELECT EMPNO, ENAME, LOC FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND LOC IN ('NEW YORK', 'DALLAS') ORDER BY 1;

--# 2O. NEW YORK 이나 DALLAS 지역에 근무하는 사원들의 사원번호와 사원이름을 사원번호 순으로 검색
SELECT EMPNO, ENAME, LOC FROM EMP NATURAL JOIN DEPT WHERE LOC IN ('NEW YORK', 'DALLAS') ORDER BY 1;

--# 22. 사원번호, 사원이름, 급여, 급여등급 급여등급별 사원번호 순으로 검색하라.
SELECT * FROM EMP;
SELECT EMPNO, ENAME, SAL, GRADE FROM EMP, SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL ORDER BY 4, 1;

--# 24. 사원번호, 사원이름, 상급자사원번호, 상급자이름을 검색(JOIN ~~ON )
SELECT A.EMPNO, A.ENAME, B.EMPNO, B.ENAME FROM EMP A JOIN EMP B ON A.MGR = B.EMPNO;

--# 26. BLAKE 사원보다 많은 급여를 받는 사원이름을 검색하라(SELF JOIN)
SELECT B.ENAME, B.SAL FROM EMP A, EMP B WHERE B.SAL > A.SAL AND A.ENAME = 'BLAKE';

--# 28. FORD사원과 같은 급여를 받는 사원의 사원번호를 검색
SELECT EMPNO FROM EMP WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME = 'FORD');

--# 30. 사원번호, 사원이름을 부하직원수가 많은 순으로 검색하라 
SELECT B.EMPNO, B.ENAME, COUNT(*) FROM EMP A JOIN EMP B ON A.MGR = B.EMPNO GROUP BY B.EMPNO, B.ENAME, A.MGR ORDER BY 3 DESC;

--# 32. SCOTT사원보다 많은 급여를 받는 사원정보를 검색하라
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT');

--# 34. 20번 부서 사원의 사원 직무와 같은 사원 직무인 다른사원 정보를 검색하라.
SELECT * FROM EMP WHERE DEPTNO <> 20 AND JOB IN (SELECT JOB FROM EMP WHERE DEPTNO = 20);

--# 36. 급여가 모든 부서들의 평균 급여보다 많은 사원 정보를 검색하라.
SELECT * FROM EMP WHERE SAL > ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

--# 연습문제
--# 1. 학생테이블 수강테이블 NUTRAL JOIN 
SELECT * FROM STUDENT NATURAL JOIN ENROL;

--# 2. 학번, 이름, 과목이름, 점수를 검색하라
SELECT * FROM SUBJECT;
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT SUBJECT.SUB_NO, SUB_PROF, SUB_NAME, ENR_GRADE 
FROM STUDENT, ENROL,SUBJECT WHERE STUDENT.STU_DEPT = SUBJECT.SUB_DEPT;

--# 4. 과목이름과 , 학번, 점수를 검색(JOIN ~ USING)
SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM ENROL; 

SELECT SUB_NAME, STU_NO, ENR_GRADE FROM SUBJECT, ENROL WHERE SUBJECT.SUB_NO = ENROL.SUB_NO;

--# 6. 점수가 60점 이상인 학생 이름을 검색하라(JOIN ~ USING)
SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM ENROL; 
SELECT STU_NAME, ENR_GRADE FROM STUDENT JOIN ENROL USING(STU_NO) WHERE ENR_GRADE > 60;

--# 8. 
 
--# 10. 
SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM ENROL; 

SELECT STU_NAME, SUB_NAME, SUB_PROF FROM STUDENT JOIN ENROL USING(STU_NO) JOIN SUBJECT USING(SUB_NO) WHERE STU_NAME = '김인중';

